/////////////////////
///// Languages /////
/////////////////////


var EN = {
    initialState : 'Initial state',
    saveAborded : 'Save aborded',
    newDocSavedAs : 'New document saved as "',
    docSaved : 'Document saved',
    docRenamedAs : 'Document renamed as "',
    setTextAlign : 'Set text-align to ',
    alignLeft : 'left',
    alignRight : 'right',
    alignCenter : 'center',
    alignJustify : 'justify',
    setFamilyFont : 'Set family-font to ',
    setFontSize : 'Set font-size to ',
    setFontColor : 'Set font color to ',
    setColor : 'Set color to ',
    chooseFile : 'Choose your file',
    confirm : 'Confirm',
    redirectLink : 'Redirection link',
    altTag : 'Alternatif tag',
    imageEdited : 'Image edited',
    newSectionAdded : 'New section added, number of sections : ',
    sectionMoved : 'Section moved',
    sectionDuplicated : 'Section duplicated, number of sections : ',
    sectionRemoved : 'Section removed, number of sections : ',
    linkColorMenu : 'Link color :',
    yourLinkHere : 'Your link here',
    applyToAllLink : 'Apply to all links',
    setLinkFontColor : 'Set link font color to ',
    setSameColorLinks : 'Set same color for links',
    textEdited : 'Text edited',
    setBackgroundColor : 'Set background color to ',
    linkAdded : 'Link added',
    textAlignMenu : 'Text Align',
    familyFontMenu : 'Font',
    fontSizeMenu : 'Font Size',
    fontColorMenu : 'Font Color',
    backgroundColorMenu : 'Background Color',
    linkMenu : 'Link',
    mobileView : 'Mobile view',
    tabletView : 'Tablet view',
    desktopView : 'Desktop view',
    save : 'Save',
    undo : 'Undo',
    redo : 'Redo',
    saveExport : 'Save and export',
    moveSection : 'Move section',
    deleteSection : 'Delete section',
    duplicateSection : 'Duplicate section',
    font : 'Change font',
    noLink : 'No link',
    noTag : 'No alternative tag',
    confirmLink : 'Confirm link',
    missing : 'missing',
    mustBeNumber : 'Value must be a number',
    modalSaveTitle : 'Save document',
    modalSaveLabel : 'Document name',
    modalSaveButton : 'Save',
    docNameDefault : 'Untitled document',
    invalidName : 'Invalid name',
    saveAs : 'Save as...'
};


var FR = {
    initialState : 'État initial',
    saveAborded : 'Sauvegarde annulé',
    newDocSavedAs : 'Nouveau document sauvegardé sous "',
    docSaved : 'Document sauvegardé',
    docRenamedAs : 'Document renommé sous "',
    setTextAlign : 'Alignement de texte : ',
    alignLeft : 'gauche',
    alignRight : 'droite',
    alignCenter : 'centré',
    alignJustify : 'justifié',
    setFamilyFont : 'Police réglée sur ',
    setFontSize : 'Taille de police à ',
    setFontColor : 'Couleur de police selectionnée : ',
    setColor : 'Couleur selectionnée : ',
    chooseFile : 'Choisir un fichier',
    confirm : 'Confirmer',
    redirectLink : 'Lien de redirection',
    altTag : 'Tag alternatif',
    imageEdited : 'Image éditée',
    newSectionAdded : 'Nouvelle section ajoutée, nombre de sections total : ',
    sectionMoved : 'Section déplacée',
    sectionDuplicated : 'Section dupliquée, nombre de sections total : ',
    sectionRemoved : 'Section supprimée, nombre de sections total : ',
    linkColorMenu : 'Couleur du lien :',
    yourLinkHere : 'Votre lien ici',
    applyToAllLink : 'Appliquer à tous les liens',
    setLinkFontColor : 'Couleur du lien appliquée : ',
    setSameColorLinks : 'Couleur des liens uniformisée',
    textEdited : 'Texte modifié',
    setBackgroundColor : "Couleur d'arrière-plan modifiée : ",
    linkAdded : 'Lien ajouté',
    textAlignMenu : 'Alignement du texte',
    familyFontMenu : 'Police',
    fontSizeMenu : 'Taille de la police',
    fontColorMenu : 'Couleur de la police',
    backgroundColorMenu : "Couleur d'arrière-plan",
    linkMenu : 'Lien',
    mobileView : 'Aperçu mobile',
    tabletView : 'Aperçu tablette',
    desktopView : 'Aperçu bureau',
    save : 'Sauvegarder',
    undo : 'Action précédente',
    redo : 'Action suivante',
    saveExport : 'Sauvegarder et exporter',
    moveSection : 'Déplacer la section',
    deleteSection : 'Supprimer la section',
    duplicateSection : 'Dupliquer la section',
    font : 'Changer la police',
    noLink : 'Pas de lien',
    noTag : 'Pas de tag alternatif',
    confirmLink : 'Confirmer le lien',
    missing : 'manquant',
    mustBeNumber : 'La valeur doit être un nombre',
    modalSaveTitle : 'Sauvegarder le document',
    modalSaveLabel : 'Nom du document',
    modalSaveButton : 'Sauvegarder',
    docNameDefault : 'Nouveau document',
    invalidName : 'Nom invalide',
    saveAs : 'Sauvegarder sous...'
};